### ISSUE TITLE
bridge2: needs to autoscroll

### ISSUE THREAD

**Issue by ajbouh** [ajbouh/substrate#116]
As messages reach the bottom of the window the transcript should automatically scroll to show them

**Comment by ajbouh** [comment]
@mgood

**Comment by mgood** [comment]
I started looking into options for auto-scrolling. I think I'll try a simpler CSS-based solution with this:
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor

That doesn't work in Safari at least, but it also doesn't support the screen media APIs needed for audio, so that limits the usefulness there for now anyways.

**Comment by ajbouh** [comment]
Two suggestions from the meeting today:

```js
div.scrollTop = div.scrollHeight
```

and

```js
transcriptElt.lastChild.scrollIntoView({ block: "end", behavior: 'smooth' })
```

**Comment by mgood** [comment]
Yeah, I'm familiar with those, though ideally I'd like to avoid the problem where you're trying to scroll up to look at an older message, but it keeps scrolling to the bottom when some new content comes in. The `overflow-anchor` property seems to handle that more gracefully, though I'll push a quick fix with `scrollIntoView` and we can come back to that later.

**Comment by ajbouh** [comment]
Usually my approach is to do what the terminal does. If you're scrolled to the bottom then I keep autoscrolling. Otherwise I leave it alone.
