### ISSUE TITLE
bridge: multiple speaker detection

### ISSUE THREAD

**Issue by ajbouh** [ajbouh/substrate#6]

**Comment by progrium** [comment]
I would recommend after #62, and once #61 includes diarization performance benchmarks, we pause and deprioritize multiple speaker detection anyway. It would just need an agent to orchestrate using the service, but based on latest prototyping and experiments it will be the opposite of low hanging fruit in terms of value for effort at this time.

**Comment by mgood** [comment]
> Mechanically I proved out an annotator based on a service around "pyannote/speaker-diarization-3.1", and it creates annotation spans for each speaker and can apply speakers to individual word annotations.

@progrium is the last iteration of this in minibridge, or was there more you had started on?
https://github.com/progrium/webrtc-sessions/blob/a4649ec881d881f22087af4f730117c6e2f4fc5e/cmd/minibridge/main.go#L209

**Comment by ajbouh** [comment]
@mgood that sounds right to me

**Comment by mgood** [comment]
Alright, I copied over the newer code from webrtc-sessions since it looks like a prior stub was copied instead.
I have something wired up, but getting a response with an empty list of speakers at the moment, so need to debug a bit more.

**Comment by mgood** [comment]
Ok, yeah in switching to sending the WAV data I had commented out the `ogg2wav` call, but still needed to use `soundfile` to decode the WAV format to raw samples.
So, I'm getting results now sending just the current audio sample.
I'll need to add back logic for collecting prior samples from the known speakers, and prepending it to the current sample in order to correlate the labels back to other known speakers.
